# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
---
include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    snippets:
  - board: seeeduino_xiao_ble
    shield: totem_right
    snippets:
  - board: seeeduino_xiao_ble
    shield: totem_dongle
    snippets:
  - board: seeeduino_xiao_ble
    shield: settings_reset
    snippets:

